version: "3"
volumes:
    redis_db:
services:
    hellofrompythonapp:
         image: hmabed/hellofrompython:final
         depends_on:
             - redis
         ports:
               - "80:80"
         networks:
               - mynetwork
         environment:
               - NOM=users
    redis:
         image: redis:latest
         command: bash -c "redis-server --appendonly yes"
         ports:
             - "6379:6379"
         networks:
             - mynetwork
         volumes:
             - redis_db:/data
networks:
    mynetwork:
    

